"""Exact-match registry of Kalshi sports series tickers.

This registry is deliberately **exact match only**.  It is not a prefix table and
it is not a pattern matcher: ``KXNFLGAME`` matches ``KXNFLGAME`` and nothing else.
That restriction is what makes ticker evidence deterministic enough to be treated
as authoritative, and it is why a ticker this registry does not know produces
``UNRESOLVED`` rather than a guess.

Verification status
-------------------
Entries marked ``verified=False`` were derived from Kalshi's published series
naming conventions but were **not** confirmed against a live ``GET /series/{ticker}``
response while this module was written.  An unverified entry can only ever fail
to match (costing a classification, never corrupting one), because a ticker that
does not exist is never returned by the API.  Audits report how many
classifications leaned on an unverified entry so the owner can confirm or prune
this table from real data.

Series metadata (tags/category/title) always outranks this table conceptually;
the classifier treats a disagreement between the two as unresolvable.
"""

from __future__ import annotations

from dataclasses import dataclass

from .sports import Sport


@dataclass(frozen=True)
class SeriesEntry:
    sport: Sport
    verified: bool


#: Exact Kalshi series tickers to sport.  Keys are compared case-insensitively
#: after stripping, but are otherwise matched literally.
SERIES_TICKER_REGISTRY: dict[str, SeriesEntry] = {
    # --- MLB ---------------------------------------------------------------
    "KXMLBGAME": SeriesEntry(Sport.MLB, verified=False),
    "KXMLBSERIES": SeriesEntry(Sport.MLB, verified=False),
    "KXWORLDSERIES": SeriesEntry(Sport.MLB, verified=False),
    "KXMLBWS": SeriesEntry(Sport.MLB, verified=False),
    # --- NFL ---------------------------------------------------------------
    "KXNFLGAME": SeriesEntry(Sport.NFL, verified=False),
    "KXNFLSPREAD": SeriesEntry(Sport.NFL, verified=False),
    "KXNFLTOTAL": SeriesEntry(Sport.NFL, verified=False),
    "KXSUPERBOWL": SeriesEntry(Sport.NFL, verified=False),
    # --- College football --------------------------------------------------
    "KXNCAAFGAME": SeriesEntry(Sport.CFB, verified=False),
    "KXNCAAFSPREAD": SeriesEntry(Sport.CFB, verified=False),
    "KXNCAAFCHAMP": SeriesEntry(Sport.CFB, verified=False),
    # --- NHL ---------------------------------------------------------------
    # VERIFIED: every one of these was returned by Kalshi's own series listing in NHL-edge-finder's live discovery
    # (run 36567059802, 2026-09-29: 75 NHL series; data/catalog/discovery_summary.json there); KXNHLGAME, KXNHLTOTAL
    # and KXNHLSPREAD were also read back market-by-market as settled 2025-26 history (KXNHLTEAMTOTAL has none yet). Still the weakest evidence level:
    # Kalshi's competition ("Pro Hockey") outranks this table and a disagreement is unresolvable, never an override.
    "KXNHLGAME": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLSPREAD": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLTOTAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLTEAMTOTAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLOT": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLOVERTIME": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL1P": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL2P": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL3P": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL1PTOTAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL2PTOTAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL3PTOTAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL1PSPREAD": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL2PSPREAD": SeriesEntry(Sport.NHL, verified=True),
    "KXNHL3PSPREAD": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLFIRSTGOAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLGOAL": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLPTS": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLAST": SeriesEntry(Sport.NHL, verified=True),
    "KXNHLSAVES": SeriesEntry(Sport.NHL, verified=True),
    # --- Tennis ------------------------------------------------------------
    # NBA: the 60 game/period/player series nba-edge-finder's live discovery (2026-09-19, 256 NBA series,
    # 6,197 markets) classes MODELABLE or BUILDABLE. L5 evidence only: never overrides a competition.
    "KXNBA1H": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1HSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1HTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1HTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1HWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1Q": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1QSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1QTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1QTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA1QWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2D": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2H": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2HSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2HTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2HTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2HWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2Q": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2QSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2QTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2QTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA2QWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3D": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3PT": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3Q": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3QSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3QTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3QTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA3QWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA4Q": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA4QSPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA4QTEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA4QTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBA4QWINNER": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAAST": SeriesEntry(Sport.NBA, verified=True),
    "KXNBABENCHPTS": SeriesEntry(Sport.NBA, verified=True),
    "KXNBABLK": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAFTM": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAGAME": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAH2H3PT": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAH2HBENCHPTS": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAH2HPRA": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAH2HPTS": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAH2HTEAM3PT": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAOT": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAOVERTIME": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPA": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPR": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPRA": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPREPACK2ML": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPREPACK3ML": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAPTS": SeriesEntry(Sport.NBA, verified=True),
    "KXNBARA": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAREB": SeriesEntry(Sport.NBA, verified=True),
    "KXNBASPREAD": SeriesEntry(Sport.NBA, verified=True),
    "KXNBASTL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBASTOCK": SeriesEntry(Sport.NBA, verified=True),
    "KXNBASTOCKS": SeriesEntry(Sport.NBA, verified=True),
    "KXNBATEAMTOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBATOTAL": SeriesEntry(Sport.NBA, verified=True),
    "KXNBAWINMARGIN": SeriesEntry(Sport.NBA, verified=True),
    # SOCCER: the 253 series soccer-edge-finder's live discovery (2026-09-27, 1,523 series) owns by the
    # exchange's own "Soccer" tag AND that carried markets. Series the exchange mis-tags (AFC Asian Cup under
    # "Soccer" with American-football wording) are deliberately absent.
    "KXAPFDDH": SeriesEntry(Sport.SOCCER, verified=True),
    "KXAPFDDHBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXAPFDDHGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXAPFDDHSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXAPFDDHTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXARGNACBBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXARGNACBGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXARGNACBSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXARGNACBTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXARGPREMDIV": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBALLONDOR": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBALLONDORAWARD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBALLONDORRANK": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBELGIANPL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIRO": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROB1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROB1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROB1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROB1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROBBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROBGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROBSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROBTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROCBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROCGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROCSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROCTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROTOPX": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBRASILEIROTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGAGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGALAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGALEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGAPOINTMARGIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGARELEGATION": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGATEAMPOINTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXBUNDESLIGATOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCANPLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCHLLDP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCHNL1GAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCHNSL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCLUBCHANGEMBAPPE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCLUBWCHOST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFGC": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNL1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNL1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNL1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNL1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNLBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNLSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONCACAFNLTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONMEBOLLIB": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCONMEBOLSUD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPAAMERICA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPAAMERICAHOST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPADELREY": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPADELREYADVANCE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPADELREYGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXCOPADOBRASIL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDENSUPERLIGA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDFBPOKAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDIMAYORBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDIMAYORGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDIMAYORSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXDIMAYORTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXECULP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLCHAMPIONSHIP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLCUP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLL1BTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLL1GAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLL1SPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLL1TOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEFLPROMO": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEKSTRAKLASA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXENGNLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLH2H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLH2HFINISH": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLLAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLLEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLPOINTMARGIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLRELEGATION": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLSEASONSTAT": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLTEAMPOINTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEPLTOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXEREDIVISIE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXFACUP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXFIFALEAVE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXFIFAWGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXHKANEKNIGHT": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLY1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLY1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLY1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLY1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLYBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLYGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLYSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXINTLFRIENDLYTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXISRNLBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXISRNLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXISRNLSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXISRNLTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXJOINCLUB": SeriesEntry(Sport.SOCCER, verified=True),
    "KXJOINLEAGUE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXJOINRONALDO": SeriesEntry(Sport.SOCCER, verified=True),
    "KXKLEAGUE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXKNVBCUP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGA2BTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGA2GAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGA2SPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGA2TOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGAGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGALAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGALEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGAPOINTMARGIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGARELEGATION": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGATEAMPOINTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLALIGATOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLAMINEYAMAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAEXPGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX1HSCORE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX2H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX2HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX2HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMX2HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXFTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXLEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXSCORE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXTEAMTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXTOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAMXTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGAPORTUGAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1GAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1LAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1LEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1POINTMARGIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1RELEGATION": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1TEAMPOINTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXLIGUE1TOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMANAGEROUTDATE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMANAGERSOUT": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS1HSCORE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS2H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS2HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS2HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLS2HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSCUP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSEAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSFTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSLEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSSCORE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSTEAMTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXMLSWEST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXNWSL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXNWSLBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXNWSLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXNWSLSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXNWSLTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXPERLIGA1": SeriesEntry(Sport.SOCCER, verified=True),
    "KXPERLIGA1GAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXPOCHETTINOOUT": SeriesEntry(Sport.SOCCER, verified=True),
    "KXPREMIERLEAGUE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEA": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEAGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEALAST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEALEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEAPOINTMARGIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEARELEGATION": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEATEAMPOINTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSERIEATOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSOCCERRETIRE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSOCCERTREBLE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSOCCERTROPHIES": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSUPERBALLONDOR": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSUPERLIG": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVK2LBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVK2LGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVK2LSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVK2LTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVKCUPADVANCE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXSVKCUPGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXTACAPORT": SeriesEntry(Sport.SOCCER, verified=True),
    "KXTHAIL1": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLBOTTOM": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLLEADER": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLLEAGUE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLROUND": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLTOP": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLTOP8": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUCLWGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUECL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFAEURO": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFAEUROQUAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANL1H": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANL1HBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANL1HSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANL1HTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLFTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLGROUPQUAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLGROUPWIN": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLROUND": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLSCORE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLTEAMTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEFANLTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUEL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXURYPD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXURYPDBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXURYPDGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXURYPDSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXURYPDTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLBTTS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLCUPADVANCE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLCUPGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLGAME": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLSPREAD": SeriesEntry(Sport.SOCCER, verified=True),
    "KXUSLTOTAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXVENFUTVE": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWC": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWCCAREERGOALS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWCHOST": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWCQUAL": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWCTEAMS": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWCW": SeriesEntry(Sport.SOCCER, verified=True),
    "KXWINSTREAKMANU": SeriesEntry(Sport.SOCCER, verified=True),
    "KXATPMATCH": SeriesEntry(Sport.TENNIS, verified=False),
    "KXWTAMATCH": SeriesEntry(Sport.TENNIS, verified=False),
    "KXUSOPEN": SeriesEntry(Sport.TENNIS, verified=False),
    "KXWIMBLEDON": SeriesEntry(Sport.TENNIS, verified=False),
}


def lookup_series_ticker(series_ticker: str | None) -> SeriesEntry | None:
    """Return the registry entry for an exact series ticker, if any."""
    if not series_ticker:
        return None
    return SERIES_TICKER_REGISTRY.get(series_ticker.strip().upper())
